### PR TITLE
Adds ability to deploy tasks

### PR DESCRIPTION
**Pull request by tdouce**
Adds ability to:
- Specify container and family for for a given service or task
- Allows users to run tasks outside the context of a service.

### CODE REVIEW

**Comment by stuarth** [comment]
would you add a note to the readme?

**Comment by tdouce** [comment]
Yep, I realized I didn't update the `README` as soon as I opened the PR.

**Comment by stuarth** [comment]
thanks!

**Comment by tdouce** [comment]
💥  Thank you!

**Pull request merged**
